server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/reservation_db
    username: postgres
    password: postgres
  sql:
      init:
        mode: always

app:
  services:
    user-url: http://user-service:8770
    club-url: http://club-service:8081