apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: review-service-cb
  namespace: padel-dev
spec:
  host: review-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 100