apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-service
  template:
    metadata:
      labels:
        app: club-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: club-service
          image: milospejic001/club-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx192m"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/club_db
            - name: SPRING_R2DBC_USERNAME
              value: "postgres"
            - name: SPRING_R2DBC_PASSWORD
              value: "postgres"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/app/config/application.yml,optional:file:/app/config/club-service.yml"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
                      httpGet:
                        path: /actuator/health
                        port: 8081
                      initialDelaySeconds: 120
                      periodSeconds: 10
                      failureThreshold: 5
          volumeMounts:
                  - name: config-volume
                    mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: config-repo