apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-composite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-composite-service
  template:
    metadata:
      labels:
        app: club-composite-service
    spec:
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: ['sh', '-c', 'until wget -q -O - http://config-server:8888/actuator/health; do echo waiting for config-server; sleep 2; done']
      containers:
        - name: club-composite-service
          image: milospejic001/club-composite-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5