apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-composite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-composite-service
  template:
    metadata:
      labels:
        app: club-composite-service
    spec:
      containers:
        - name: club-composite-service
          image: milospejic001/club-composite-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx192m"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/app/config/application.yml,optional:file:/app/config/club-composite-service.yml"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
                  - name: config-volume
                    mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: config-repo