apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command: 
            - sh
            - -c
            - |
              until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done
              until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done
      containers:
        - name: reservation-service
          image: milospejic001/reservation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx192m"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/reservation_db
            - name: SPRING_R2DBC_USERNAME
              value: "postgres"
            - name: SPRING_R2DBC_PASSWORD
              value: "postgres"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: APP_SERVICES_USER_URL
              value: http://user-service:8770
            - name: APP_SERVICES_CLUB_URL
              value: http://club-service:8081
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/app/config/application.yml,optional:file:/app/config/reservation-service.yml"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
                      httpGet:
                        path: /actuator/health
                        port: 8082
                      initialDelaySeconds: 120
                      periodSeconds: 10
                      failureThreshold: 5
          volumeMounts:
                  - name: config-volume
                    mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: config-repo