apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: user-service
          image: milospejic001/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8770
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx192m"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/user_db
            - name: SPRING_R2DBC_USERNAME
              value: "postgres"
            - name: SPRING_R2DBC_PASSWORD
              value: "postgres"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/app/config/application.yml,optional:file:/app/config/user-service.yml"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          readinessProbe:
                      httpGet:
                        path: /actuator/health
                        port: 8770
                      initialDelaySeconds: 120
                      periodSeconds: 10
                      failureThreshold: 5
          volumeMounts:
                  - name: config-volume
                    mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: config-repo