apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-hands-on-config
  namespace: kube-system
data:
  fluentd-hands-on.conf: |
    # 1. Tag logs from the 'padel-dev' namespace as Spring Boot logs
    <match kubernetes.**padel-dev**>
      @type rewrite_tag_filter
      <rule>
        key log
        pattern ^(.*)$
        tag spring-boot.${tag}
      </rule>
    </match>

    # 2. Process stack traces for Spring Boot tagged logs
    <match spring-boot.**>
      @type detect_exceptions
      languages java
      message log
      remove_tag_prefix spring-boot
      multiline_flush_interval 5
    </match>

    # 3. Parse JSON logs to extract trace and span IDs for correlation
    <filter spring-boot.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type json
      </parse>
    </filter>