apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data/postgres/postgres-init-configmap.yml
  - data/postgres/postgres-pvc.yml
  - data/postgres/postgres-deployment.yml
  - data/postgres/postgres-service.yml
  - data/rabbitmq/rabbitmq-deployment.yml
  - data/rabbitmq/rabbitmq-service.yml


  - components/deployments/user-service-deployment.yml
  - components/deployments/club-service-deployment.yml
  - components/deployments/reservation-service-deployment.yml
  - components/deployments/review-service-deployment.yml
  - components/deployments/notification-service-deployment.yml
  - components/deployments/club-composite-service-deployment.yml
  
  - components/services/user-service-service.yml
  - components/services/club-service-service.yml
  - components/services/reservation-service-service.yml
  - components/services/review-service-service.yml
  - components/services/notification-service-service.yml
  - components/services/club-composite-service-service.yml

  - istio/istio-gateway.yml
  - istio/istio-virtual-service.yml
  - istio/istio-circuit-breaker.yml
  - istio/istio-envoy-filter.yml
  - istio/istio-authorization.yml
  #- istio/istio-authentication.yml

configMapGenerator:
  - name: config-repo
    files:
      - config-repo/application.yml
      - config-repo/user-service.yml
      - config-repo/club-service.yml
      - config-repo/reservation-service.yml
      - config-repo/review-service.yml
      - config-repo/notification-service.yml
      - config-repo/club-composite-service.yml