apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - security/istio-peer-authentication.yml

namespace: padel-prod

labels:
  - pairs:
      environment: production
      project: padel-reservation-system

patches:
  - path: replica_patch.yaml
    target:
      kind: Deployment
      name: ".*-service"

configMapGenerator:
- name: env-config
  literals:
    - SPRING_PROFILES_ACTIVE=prod
    - LOGGING_LEVEL_ROOT=INFO